backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to main)

media_folder: "/public/uploads/"
public_folder: "uploads"

collections:
    - name: "blog"
      label: "Blog"
      label_singular: "Post"
      folder: "src/pages/posts"
      create: true
      delete: true
      slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
      fields:
          - { name: "title", label: "Título", widget: "string" }
          - { name: "body", widget: "markdown", label: "Post Body" }
          - { label: "Tags", name: "tags", widget: "list" }
